title:      Moonwalk
author:     Liam Carroll
email:      liam.robert.carroll@gmail.com
url:        https://lrcarroll.github.io # root address of the site
baseurl:    ""
description: > # description of the site (multiple lines allowed)# A summary of my research and some other things I find interesting and want other people to see.

Kia Ora, my name is Liam Carroll
I am a postdoctoral researcher at the University of New South Wales, Australia, where I work on developing electrochemical aptamer-based sensors. I completed my PhD in chemistry from the University of Canterbury, New Zealand, where I focused on the chemical modification of transparent semiconducting materials for use in electronic devices.
In addition to my PhD, I hold a BSc(Hons) in chemistry and a BSc majoring in chemistry and mathematics, both from the University of Canterbury. My research interests include nanotechnology, electrochemistry, and bioanalytical chemistry.
On this website, you'll find updates on my current research, publications, and other projects. Please note that the views expressed here are my own and not those of any organisation I am affiliated with. I will update this page when time permits, so please check back periodically. If you have any interesting opportunities or collaborations, please feel free to contact me below.

permalink: /:slug

favicon: "/favicon_io/android-chrome-512x512.png" # relative path to site's favicon
site_favicon: "/favicon.ico"

twitter:
    username: abhinav # update or delete this
    card: summary_large_image

#theme: moonwalk # if you are using GitHub Pages, change it to remote_theme: abhinavs/moonwalk
remote_theme: abhinavs/moonwalk

theme_config:
  appearance: "auto" # can be "light", "dark" or "auto"
  appearance_toggle: true # if appearance can be switched by user
  back_home_text: "< HOME" # customize text for homepage link in post layout
  date_format: "%Y-%m-%d" # customize how date is formatted
  show_description: true # show blog description
  show_navbar: true # show horizontal navbar
  show_footer: true # show footer links in home page,add in _data/home.yml
  show_copyright: true # show copyright notice in footer
  # following keys are using to create home layout
  show_projects: true # show projects as cards, add in _data/home.yml
  show_blog: true # show blog posts added in _posts
  show_old_projects: false # show old projects as cards, add in _data/home.yml
  show_misc_list: true # show generic vertical list for misc details, add _data/home.yml
  # options for "home" page
  home:
    title_projects: Reasearch
    title_misc_list: Details
    title_blog: Blog
    title_old_projects: Old Projects

soopr:
  publish_token: "" # sign up at https://www.soopr.co to get your publish token and personalize share and reaction options

highlighter: rouge

sass:
  style: :compressed

plugins:
  - jekyll-feed
  - jekyll-seo-tag
