title:      Liam's World
author:     Liam Carroll
email:      liam.robert.carroll@gmail.com
url:        https://lrcarroll.github.io # root address of the site
baseurl:    ""
description: > # description of the site (multiple lines allowed)
  Kia Ora, my name is Liam Carroll.

  I am currently a postdoctoral research associate at the University of New South Wales in Australia, where I work on developing electrochemical aptamer-based sensors.

  On this website, you'll find updates on my current research, publications, and other projects.

permalink: /:slug

# favicon: "/favicon_io/android-chrome-512x512.png" # relative path to site's favicon
#site_favicon: "favicon.ico"
favicon: "./logo.png" # relative path to site's favicon

twitter:
    username: abhinav # update or delete this
    card: summary_large_image

#theme: moonwalk # if you are using GitHub Pages, change it to remote_theme: abhinavs/moonwalk
remote_theme: abhinavs/moonwalk

theme_config:
  appearance: "auto" # can be "light", "dark" or "auto"
  appearance_toggle: true # if appearance can be switched by user
  back_home_text: "< Return" # customize text for homepage link in post layout
  date_format: "%Y-%m-%d" # customize how date is formatted
  show_description: false # show blog description
  show_navbar: true # show horizontal navbar
  show_footer: true # show footer links in home page,add in _data/home.yml
  show_copyright: true # show copyright notice in footer
  # following keys are using to create home layout
  show_projects: true # show projects as cards, add in _data/home.yml
  show_blog: true # show blog posts added in _posts
  show_old_projects: false # show old projects as cards, add in _data/home.yml
  show_misc_list: false # show generic vertical list for misc details, add _data/home.yml
  # options for "home" page
  home:
    title_projects: Projects
    title_misc_list: Details
    title_blog: Blog
    title_old_projects: Old Projects

soopr:
  publish_token: "" # sign up at https://www.soopr.co to get your publish token and personalize share and reaction options

highlighter: rouge

sass:
  style: :compressed

plugins:
  - jekyll-feed
  - jekyll-seo-tag
